### ISSUE TITLE
ControlSystemAdapterSharedPVSupport::read might accidentally use null value

### ISSUE THREAD

**Issue by smarsching** [aquenos/ChimeraTK-ControlSystemAdapter-EPICS#2]
@mhier reported a bug in `ControlSystemAdapterSharedPVSupport::read`:

When the underlying `ProcessArray` supports `AccessMode::wait_for_new_data`, the `lastValue` (and `lastVersionNumber`) are used. This is problematic, because `lastValue` might not have been initialized yet and might thus be `null`.

This will lead to a null-pointer dereference if the calling code expects the returned tuple to always contain a non-null value (and accoding the the original report, the EPICS IOC does indeed crash).

For a `ProcessArray` that does not support `AccessMode::wait_for_new_data`, this might also happen if `readLatest` returns `false`, though I am not entirely sure yet whether this can ever happen.

**Comment by mhier** [comment]
Without `AccessMode::wait_for_new_data`, all `read`-like functions act like `readLatest` and always succeed (i.e. return `true`). Different behaviour would be a bug in the `ProcessArray` implementation.
